// <auto-generated />
using DagnysBakeryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DagnysBakeryAPI.Migrations
{
    [DbContext(typeof(BakeryContext))]
    [Migration("20250110143543_ProductsController")]
    partial class ProductsController
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DagnysBakeryAPI.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerKg")
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ArticleNumber = "A001",
                            Name = "Mjöl",
                            PricePerKg = 10.5m,
                            SupplierId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            ArticleNumber = "A001",
                            Name = "Mjöl",
                            PricePerKg = 9.5m,
                            SupplierId = 2
                        });
                });

            modelBuilder.Entity("DagnysBakeryAPI.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            Address = "Mjölgatan 1",
                            ContactPerson = "Jacob Ahlström",
                            Email = "jacobsmjöl@gmail.com",
                            Name = "Jacobs Mjöl AB",
                            PhoneNumber = "0761123456"
                        },
                        new
                        {
                            SupplierId = 2,
                            Address = "Mjölgatan 2",
                            ContactPerson = "Fabian Ahlström",
                            Email = "fabiansmjöl@gmail.com",
                            Name = "Fabians Mjöl AB",
                            PhoneNumber = "0761123457"
                        });
                });

            modelBuilder.Entity("DagnysBakeryAPI.Entities.Product", b =>
                {
                    b.HasOne("DagnysBakeryAPI.Entities.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("DagnysBakeryAPI.Entities.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
